"""Add mail

Revision ID: 4884fd816880
Revises: 97b3e2121afe
Create Date: 2025-05-29 00:55:51.464292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4884fd816880'
down_revision = '97b3e2121afe'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('email_confirmed', sa.Boolean(), nullable=True))

    op.execute("UPDATE users SET email = 'user_' || id || '@example.com' WHERE email IS NULL;")
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('email', nullable=False)
        batch_op.create_unique_constraint('uq_users_email', ['email'])



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email_confirmed')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
